authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

geekshop/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp



urlpatterns = [
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name="contact"),
    path('about/', mainapp.about, name='about'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth'))
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name = 'возраст')

mainapp/models.py
from django.db import models

class Page(models.Model):
    name = models.CharField(unique=True, max_length=64)
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='pages_images', blank=True)

    def __str__(self):
        return f"{self.name}"

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm

from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))  

mainapp/views.py
from django.shortcuts import render
from .models import Page


def main(request):
    page = Page.objects.all()[0]
    context = {'page': page}
    return render(request, 'mainapp/index.html', context)

def contact(request):
    page = Page.objects.all()[1]
    context = {'page': page}
    return render(request, 'mainapp/contact.html', context)

def about(request):
    page = Page.objects.all()[2]
    context = {'page': page}
    return render(request, 'mainapp/about.html', context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

{% endblock %}

mainapp/templates/mainapp/Templates/main.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">

        {% block content %}

        {% endblock %}

	</div>

    {% block footer %}
        <div class="footer">
            <div class="text-footer">
               <h3>контакты</h3>
            </div>
            <div class="text-footer">
               <h3>полезная информация</h3>
            </div>
        </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/Templates/menu.html
<ul>
    <li><a href="{% url 'main' %}">На главную</a></li>
    <li><a href="{% url 'contact' %}">Контакты</a></li>
    <li><a href="{% url 'about' %}">О ресурсе</a></li>
</ul>

mainapp/templates/mainapp/about.html
{% extends 'mainapp/Templates/main.html' %}

{% block content %}
<h1 class="about">{{page.name}}</h1>
<p>{{page.text}}</p>
<img src="/media/{{page.image}}" alt="" width=100px, height=100px>
 {% include 'mainapp/Templates/menu.html' %}

{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/Templates/main.html' %}

{% block content %}
<h1 class="contact">{{page.name}}</h1>
<p>{{page.text}}</p>
<img src="/media/{{page.image}}" alt="" width=100px, height=100px>
 {% include 'mainapp/Templates/menu.html' %}
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/Templates/main.html' %}

{% block content %}
<h1 class="main">{{page.name}}</h1>
<p>{{page.text}}</p>
<img src="/media/{{page.image}}" alt="" width=100px, height=100px>
 {% include 'mainapp/Templates/menu.html' %}
{% endblock %}